server:
  port: 9393

spring:
  output:
    ansi:
      enabled: always


management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
